#!/bin/bash
for file; do
    test -f "$file" || { echo not exist sql file: $file; exit; }
done

eval $(egrep -v '^;' $(dirname $0)/db.ini)
cmd="mysql -t -h$host -u$user -p$password --default-character-set=utf8"

$cmd -e "create database if not exists \`$database\` default charset=utf8; "

if (( $# > 0 )); then
    for file; do
        $cmd "$database" < $file
    done
else
    $cmd
fi

