#!/usr/bin/php
<?php
# vim: ft=php

define('APP_ROOT', dirname(__FILE__));

class App
{
    static function run_command()
    {
        ini_set('log_errors', 1);
        ini_set('display_errors', 0);
        global $argv;
        $run = array_shift($argv);
        if(!isset($argv[0]) || !($target = $argv[0]))
        {
            echo "usage: $run <file name> args...\n";
            return;
        }
        $target = APP_ROOT . '/' . $target;
        if (file_exists($target)) require_once $target;
        else echo "file not exist: $target\n";
    }
}

App::run_command();


