#!/bin/bash
dir=$(realpath -s "$0"/../../..)

if test -z "$1"; then 
    domain=izheko.dev
elif test "$1" = production; then 
    domain=izheko.cn
else
    echo unknow argument: "$1"
    exit
fi

if test "$1" = production; then 
    tmp_dir="$dir"/grab/tmp
    test -d "$tmp_dir" || mkdir --mode=755 "$tmp_dir"
    chown www-data:www-data "$tmp_dir"
    replace APP_ROOT "$dir/grab"  < "$dir"/grab/crontab | crontab -u www-data -
    (cd "$dir/grab"; php run command/item_update_daemon.cmd.php >> tmp/item_update_daemon.log 2>&1 &)
fi

pic_dir="$dir"/static/public/pic
test -d "$pic_dir" || mkdir --mode=755 "$pic_dir"
chown www-data:www-data "$pic_dir"


cache_dir="$dir"/www/public/cache
test -d "$cache_dir" || mkdir --mode=755 "$cache_dir"
chown www-data:www-data "$cache_dir"
replace TOP_DOMAIN $domain APP_ROOT "$dir/www"    < "$dir"/www/nginx    > /etc/nginx/sites-enabled/www.nginx

replace TOP_DOMAIN $domain APP_ROOT "$dir/static" < "$dir"/static/nginx > /etc/nginx/sites-enabled/static.nginx

tmp_dir="$dir"/manage/tmp
test -d "$tmp_dir" || mkdir --mode=755 "$tmp_dir"
"$(dirname "$0")"/gen-htpasswd > "$tmp_dir"/htpasswd
replace TOP_DOMAIN $domain APP_ROOT "$dir/manage" < "$dir"/manage/nginx > /etc/nginx/sites-enabled/manage.nginx

nginx -s reload

