#!/bin/bash
apt-get install nginx mysql-client-5.5 mysql-server-5.5 
apt-get install php5-cli php5-mysqlnd php5-curl php5-fpm 

dir=$(dirname $0)/..
$dir/db/run $dir/db/sql/create_items.mysql
$dir/db/load

