#!/bin/bash
apt-get install nginx mysql-client-5.5 mysql-server-5.5 
apt-get install php5-cli php5-mysqlnd php5-curl php5-fpm 

dir=$(dirname $0)/..
$dir/db/run $dir/db/sql/create_items.mysql
$dir/db/load

replace APP_ROOT '' < $dir/../web/www.nginx       > /etc/nginx/sites-enabled/www.nginx
replace APP_ROOT '' < $dir/../manage/manage.nginx > /etc/nginx/sites-enabled/manage.nginx

nginx -s reload

