#!/bin/bash
dir=$(dirname $0)/..
eval $(egrep -v '^;' $dir/config/db.ini)
cmd="mysqldump -h$host -u$user -p$password $database"
$cmd types > $dir/sql/types.dump.mysql
$cmd -w"type_id>0 or parent_cid=0" categories > $dir/sql/categories.dump.mysql

