#!/bin/bash
dir=$(dirname $0)/..
eval $(egrep -v '^;' $dir/config/db.ini)
mysqldump -h$host -u$user -p$password $database types > $dir/sql/types.dump.mysql
mysqldump -h$host -u$user -p$password -w"type_id>0 or parent_cid=0" $database categories > $dir/sql/categories.dump.mysql

