#!/bin/bash
(( $# == 1 || $# == 2 )) || { echo "usage: $0 <num_iid> [tmall | taobao]"; exit; }
[[ $1 =~ ^[0-9]+$ ]] && num_iid=$1 || { echo "invalid num_iid: $1"; exit; }
(( $# == 2 )) && {
  [[ $2 = 'tmall' || $2 = 'taobao' ]] && which=$2 || { echo "unknow argument: $2"; exit; }
} || which=tmall

agent='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.64 Safari/537.31'
if [[ $which = 'taobao' ]]; then
    refer="http://item.taobao.com/item.htm?id=$num_iid"
    url="http://ajax.tbcdn.cn/json/umpStock.htm?itemId=$num_iid&p=1&rcid=28&sts=341317634,1170940438677291012,1225260582244974720,1166502676530463747&chnl=pc&price=9990&sellerId=10142375&shopId=&cna=M5sSCm8Hwi0CAbaW6nJssBNK&ref=&buyerId=174294739&nick=bughou&tg=1316864&tg2=67108872&tg3=1224979098644774912&tg4=4573968373776384&tg6=0"
else
    refer="http://detail.tmall.com/item.htm?id=$num_iid"
    url="http://mdskip.taobao.com/core/initItemDetail.htm?itemId=$num_iid"
fi

wget -O - -U "$agent" --refer "$refer"  "$url" | vim -


