../public/css/main.css: base.css header.css sidebar.css content.css condition.css items.css footer.css
	cat base.css header.css sidebar.css content.css condition.css items.css footer.css > ../public/css/main.css
