../public/css/main.css : common.css header.css
	cat common.css header.css > ../public/css/main.css

../public/css/main2.css : common.css header2.css
	cat common.css header2.css > ../public/css/main2.css

../public/css/main3.css : common.css header3.css
	cat common.css header3.css > ../public/css/main3.css

all : ../public/css/main.css ../public/css/main2.css ../public/css/main3.css

