all : ../public/css/main1.css ../public/css/main2.css ../public/css/main3.css

../public/css/main1.css : common.css header1.css
	cat common.css header1.css > ../public/css/main1.css

../public/css/main2.css : common.css header2.css
	cat common.css header2.css > ../public/css/main2.css

../public/css/main3.css : common.css header3.css
	cat common.css header3.css > ../public/css/main3.css

