#!/bin/bash
dir=$(realpath -s "$0"/../../..)

if test "$1" = production; then 
    ds=cn
else
    ds=dev
fi

cache_dir="$dir"/web/public/cache
test -d "$cache_dir" || mkdir "$cache_dir"
chown www-data:www-data "$cache_dir"
replace DOMAIN_SUFFIX $ds APP_ROOT "$dir/web"    < "$dir"/web/nginx    > /etc/nginx/sites-enabled/www.nginx
replace DOMAIN_SUFFIX $ds APP_ROOT "$dir/manage" < "$dir"/manage/nginx > /etc/nginx/sites-enabled/manage.nginx
test -d "$dir"/manage/tmp || mkdir "$dir"/manage/tmp
"$(dirname "$0")"/gen-htpasswd bughou death          > "$dir"/manage/tmp/htpasswd
nginx -s reload

