#!/bin/bash
cd "$(dirname "$0")"

eval $(egrep -v '^;' db.ini)
cmd="mysqldump -h$host -u$user -p$password $database --default-character-set=utf8"

$cmd                                    types > dump_sql/types.dump.mysql
$cmd -w"type_id>0 or parent_cid=0" categories > dump_sql/categories.dump.mysql

